#!/bin/bash

type=$1
lib=$2

if [ "$type" = "server" ]; then
    echo "installing $lib for server"
    cd server && npm i "$lib"
elif [ "$type" = "client" ]; then
    echo "installing $lib for client"
    cd client && npm i "$lib"
elif [ "$type" = "both" ]; then
    echo "Installing $lib for both networks"
    cd client && npm i "$lib"
    cd ../server && npm i "$lib"
else 
    echo  "\nType argument is missing or invalid"
fi
